# Generated by Django 4.2.5 on 2023-09-26 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'assembly',
            },
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('gene_id', models.IntegerField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=50)),
                ('stable_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'gene',
            },
        ),
        migrations.CreateModel(
            name='GeneTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'gene_test',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='genes_main.assembly')),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('transcript_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stable_id', models.CharField(max_length=50)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='genes_main.gene')),
            ],
            options={
                'db_table': 'transcript',
            },
        ),
        migrations.CreateModel(
            name='TranscriptLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='genes_main.region')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='genes_main.transcript')),
            ],
            options={
                'db_table': 'transcript_location',
            },
        ),
    ]
