# Generated by Django 4.2.4 on 2023-09-26 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genes_main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneTest',
        ),
    ]
